--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE (
 TPL_ID	 NUMBER NOT NULL ENABLE 
,TPL_NAME	VARCHAR2(128 CHAR)
,PRIORITY_LIST	VARCHAR2(128 CHAR)	
,TPL_LANGUAGE	VARCHAR2(20 CHAR) NOT NULL ENABLE
,LOCAL_TPL_ID	NUMBER	
,DEFAULT_TEMPLATE_FLG	NUMBER	
,MESSAGE_CODE	VARCHAR2(100 CHAR)	
,CREATED_DTTM	TIMESTAMP(6) DEFAULT SYSTIMESTAMP
,USER_NAME	VARCHAR2(128 BYTE)	
,LOGICAL_APPLICATION	VARCHAR2(50 CHAR) NOT NULL ENABLE
,UPDATED_DTTM	TIMESTAMP(6) DEFAULT SYSTIMESTAMP
,INAPP_DESCRIPTION	VARCHAR2(1024 CHAR)	
,STATUS	VARCHAR2(20 CHAR)	
,APPROVED_BY	VARCHAR2(128 CHAR)	
,BAPP_ID	VARCHAR2(20 CHAR) NOT NULL ENABLE
,CONSTRAINT "DICT_IAP_TEMPLATE_BASE_PK" PRIMARY KEY ("TPL_ID") USING INDEX  ENABLE
)
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO HCI_APP_SELECT
/
GRANT SELECT ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO SAS_INT_COMMUNICATION_RO
/
GRANT SELECT ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO HCPH_INT_COMM_RO
/
GRANT SELECT, INSERT, UPDATE, DELETE ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO SAS_INT_COMM_DICT_RW
/
GRANT SELECT, INSERT, UPDATE, DELETE ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO MA_TEMP
/ 
GRANT SELECT, INSERT, UPDATE, DELETE ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO OFS_USER
/
GRANT UPDATE ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO HCI_APP_UPDATE
/
GRANT SELECT ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO HCI_RO_INT_COMMUNICATION
/
GRANT INSERT ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO HCI_APP_INSERT
/
GRANT SELECT, INSERT, UPDATE ON INT_COMMUNICATION.DICT_IAP_TEMPLATE_BASE TO APPSUPPORT
/