--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.IAP_OUTPUT_LOAD contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE INT_COMMUNICATION.IAP_OUTPUT_LOAD (
 RESPTRACKING_CD	VARCHAR2(19 CHAR)
,ID_CUID	NUMBER	
,BAPP_ID	VARCHAR2(30 CHAR)	
,TPL_ID	NUMBER	
,DATE_EFFECTIVE	DATE	
,PROCESSED_FLG	NUMBER	
,PROCESSED_DTTM	DATE	
,LOCAL_TPL_ID	NUMBER	
,MESSAGE_CODE	VARCHAR2(30 CHAR)
,IL_COMMUNICATION_ID	NUMBER NOT NULL ENABLE
,COMMUNICATION_CD	VARCHAR2(30 CHAR)	
,CH_ID	NUMBER	NOT NULL ENABLE
,CREATED_DTTM	DATE	
,UPDATE_DTTM	DATE	
,COMMUNICATION_END	DATE
,TRACK_RESPONSE_DAYS	NUMBER(38,0)
,LOGICAL_APPLICATION	VARCHAR2(50 CHAR)
,CONSTRAINT "IAP_OUTPUT_LOAD_PK" PRIMARY KEY ("IL_COMMUNICATION_ID") USING INDEX  ENABLE
)
PARTITION BY LIST ("PROCESSED_FLG")  (PARTITION "PROCESSED_FLG_1"  VALUES (1) , PARTITION "PROCESSED_FLG_NON_1"  VALUES (DEFAULT) )  
ENABLE ROW MOVEMENT  PARALLEL 24 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
CREATE INDEX "INT_COMMUNICATION"."IAP_OUTPUT_LOAD_FK2_IND" ON "INT_COMMUNICATION"."IAP_OUTPUT_LOAD" ("COMMUNICATION_CD")  LOCAL (PARTITION "PROCESSED_FLG_1" NOCOMPRESS , PARTITION "PROCESSED_FLG_NON_1" NOCOMPRESS ) 
/
CREATE INDEX "INT_COMMUNICATION"."IAP_OUTPUT_LOAD_FK1_IND" ON "INT_COMMUNICATION"."IAP_OUTPUT_LOAD" ("ID_CUID") 
/
CREATE INDEX "INT_COMMUNICATION"."IAP_OUTPUT_LOAD_FK3_IND" ON "INT_COMMUNICATION"."IAP_OUTPUT_LOAD" ("CH_ID") 
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO SAS_INT_COMMUNICATION_RO
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO INT_ETL
/
GRANT SELECT, INSERT, UPDATE, DELETE ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO MA_TEMP
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO HCPH_INT_COMM_RO
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO HCI_APP_SELECT
/
GRANT UPDATE ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO HCI_APP_UPDATE
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO HCI_RO_INT_COMMUNICATION
/
GRANT INSERT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO HCI_APP_INSERT
/
GRANT SELECT, INSERT, UPDATE ON INT_COMMUNICATION.IAP_OUTPUT_LOAD TO APPSUPPORT
/