--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.IAP_UNMAP_RESP contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE "INT_COMMUNICATION"."IAP_UNMAP_RESP" (
RESPONSE_INPUT_LOAD_ID	NUMBER	NOT NULL ENABLE
,CHANNEL_CD	VARCHAR2(10 CHAR)	
,IL_COMMUNICATION_ID	NUMBER	
,RESPONSE_NM	VARCHAR2(100 CHAR)
,RESPONSE_DTTM	TIMESTAMP(6) WITH TIME ZONE	
,PHONE_NUMBER	VARCHAR2(250 CHAR)	
,RESPONSE_COMMENT	VARCHAR2(1024 CHAR)
,PROCESSED_FLG	NUMBER(10,0)	
,PROCESSED_DTTM	DATE	
,CREATED_DTTM	DATE	
,BAPP_ID	VARCHAR2(30 CHAR)	
,ESP_CORRELATION_ID	VARCHAR2(100 CHAR)	
,UPDATE_DTTM	DATE	
,CONSTRAINT "IAP_UNMAP_REST_PK" PRIMARY KEY ("RESPONSE_INPUT_LOAD_ID") USING INDEX  ENABLE
)
PARTITION BY LIST ("PROCESSED_FLG")  (PARTITION "PROCESSED_FLG_1"  VALUES (1) , PARTITION "PROCESSED_FLG_NON_1"  VALUES (DEFAULT) )  
ENABLE ROW MOVEMENT  PARALLEL 24 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT ON INT_COMMUNICATION.IAP_UNMAP_RESP TO SAS_INT_COMMUNICATION_RO
/
GRANT SELECT ON INT_COMMUNICATION.IAP_UNMAP_RESP TO INT_ETL
/
GRANT SELECT, INSERT, UPDATE, DELETE ON INT_COMMUNICATION.IAP_UNMAP_RESP TO MA_TEMP
/
GRANT SELECT ON INT_COMMUNICATION.IAP_UNMAP_RESP TO HCPH_INT_COMM_RO
/
GRANT SELECT ON INT_COMMUNICATION.IAP_UNMAP_RESP TO HCI_APP_SELECT
/
GRANT UPDATE ON INT_COMMUNICATION.IAP_UNMAP_RESP TO HCI_APP_UPDATE
/
GRANT SELECT ON INT_COMMUNICATION.IAP_UNMAP_RESP TO HCI_RO_INT_COMMUNICATION
/
GRANT INSERT ON INT_COMMUNICATION.IAP_UNMAP_RESP TO HCI_APP_INSERT
/
GRANT SELECT, INSERT, UPDATE ON INT_COMMUNICATION.IAP_UNMAP_RESP TO APPSUPPORT
/