--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE (
 RESPTRACKING_CD	VARCHAR2(19 CHAR)
,ID_CUID	NUMBER	
,BAPP_ID	VARCHAR2(30 CHAR)	
,TPL_ID	NUMBER	
,DATE_EFFECTIVE	DATE	
,PROCESSED_FLG	NUMBER	
,PROCESSED_DTTM	DATE	
,LOCAL_TPL_ID	NUMBER	
,MESSAGE_CODE	VARCHAR2(30 CHAR)
,IL_COMMUNICATION_ID	NUMBER NOT NULL ENABLE
,COMMUNICATION_CD	VARCHAR2(30 CHAR)	
,CH_ID	NUMBER	NOT NULL ENABLE
,CREATED_DTTM	DATE	
,UPDATE_DTTM	DATE	
,COMMUNICATION_END	DATE
,TRACK_RESPONSE_DAYS	NUMBER(38,0)
,LOGICAL_APPLICATION	VARCHAR2(50 CHAR)
,ARCHIVED_DTTM	DATE DEFAULT SYSDATE
,CONSTRAINT "IAP_OUTPUT_LOAD_ARCHIVE_PK" PRIMARY KEY ("IL_COMMUNICATION_ID") USING INDEX  ENABLE
)
PARTITION BY RANGE ("ARCHIVED_DTTM") INTERVAL (NUMTODSINTERVAL(1, 'DAY'))  (PARTITION "PINIT"  VALUES LESS THAN (TO_DATE(' 2026-01-01 00:00:00', 'SYYYY-MM-DD HH24:MI:SS', 'NLS_CALENDAR=GREGORIAN')) )
ENABLE ROW MOVEMENT  PARALLEL 8 
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
CREATE INDEX "INT_COMMUNICATION"."IAP_OUTPUT_LOAD_ARCHIVE_FK1_IND" ON "INT_COMMUNICATION"."IAP_OUTPUT_LOAD_ARCHIVE" ("ID_CUID") 
/
CREATE INDEX "INT_COMMUNICATION"."IAP_OUTPUT_LOAD_ARCHIVE_FK3_IND" ON "INT_COMMUNICATION"."IAP_OUTPUT_LOAD_ARCHIVE" ("CH_ID")
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO SAS_INT_COMMUNICATION_RO
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO INT_ETL
/
GRANT SELECT, INSERT, UPDATE, DELETE ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO MA_TEMP
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO HCPH_INT_COMM_RO
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO HCI_APP_SELECT
/
GRANT UPDATE ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO HCI_APP_UPDATE
/
GRANT SELECT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO HCI_RO_INT_COMMUNICATION
/
GRANT INSERT ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO HCI_APP_INSERT
/
GRANT SELECT, INSERT, UPDATE ON INT_COMMUNICATION.IAP_OUTPUT_LOAD_ARCHIVE TO APPSUPPORT
/
