--liquibase formatted.sql
--changeset michael.cawayan:INT_COMMUNICATION.V_ESP_V_ESP_IAP_INPUT_LOAD contextFilter:PH endDelimiter:/ runOnChange:true

DECLARE    
exc_already_exists EXCEPTION;    
PRAGMA EXCEPTION_INIT(exc_already_exists, -0955);
BEGIN    
EXECUTE IMMEDIATE q'{
CREATE TABLE INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD (
 MSID	VARCHAR2(1024 CHAR)	
,RESPONSE_NM	VARCHAR2(100 CHAR)
,CLIENT_TIME	VARCHAR2(1024 CHAR)	
,ESP_CORRELATION_ID	VARCHAR2(100 CHAR)
,BAPP_ID	VARCHAR2(30 CHAR)
)
}';
EXCEPTION    
WHEN exc_already_exists 
THEN NULL;
END;
/
GRANT SELECT ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO SAS_INT_COMMUNICATION_RO
/
GRANT SELECT ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO INT_ETL
/
GRANT SELECT, INSERT, UPDATE, DELETE ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO MA_TEMP
/
GRANT SELECT ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO HCPH_INT_COMM_RO
/
GRANT SELECT ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO HCI_APP_SELECT
/
GRANT UPDATE ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO HCI_APP_UPDATE
/
GRANT SELECT ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO HCI_RO_INT_COMMUNICATION
/
GRANT INSERT ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO HCI_APP_INSERT
/
GRANT SELECT, INSERT, UPDATE ON INT_COMMUNICATION.V_ESP_IAP_INPUT_LOAD TO APPSUPPORT
/